version: '3.8'

services:
  # database engine
  postgres_db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      #allow *.sql, *.sql.gz, or *.sh and is execute only if data directory is empty
    - ./dbfiles:/docker-entrypoint-initdb.d
    - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
  # Database admin service
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    depends_on:
      - postgres_db
    ports:
      - "9090:8080"
  # backend billing app backend service
  billingapp-back:
    build:
      # context: le decimos que parta desde la carpeta java, aquí buscaremos el jar mas abajo
      # no dejar espacios luego del igual
      context: ./java 
      args:
        - JAR_FILE=*.jar
        - DB_PASSWORD=qwerty
    container_name: billingApp-back
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    depends_on:
      - postgres_db
    ports:
      - 8080:8080
  # backend billing app frontend service
  billingapp-front:
    build:
        context: ./angular 
    container_name: billingApp-front
    depends_on:
      - billingapp-back
    ports:
      - 80:80
volumes:
  postgres_data:
    external: false

